apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: resume-app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: resume-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: resume-app
    spec:
      containers:
        - name: backend
          image: dishanttwi123/ai-resume-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
